name: jump_sc
channels:
  - conda-forge
dependencies:
  - conda-forge::python
  - conda-forge::boto3
  - conda-forge::jupyter
  - conda-forge::jupyterlab
  - conda-forge::ipykernel
  - conda-forge::nb_conda_kernels
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::pandas
  - conda-forge::scipy
  - conda-forge::numpy
  - conda-forge::scikit-learn
  - conda-forge::plotnine
  - conda-forge::umap-learn
  - conda-forge::matplotlib
  - pip:
    - cytotable==0.0.1
